server:
  servlet:
    context-path: /api
  port: 8081

spring:
 mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
 datasource:
   url: jdbc:mysql://localhost:3306/tasks?serverTimezone=UTC
   username: root 
   password: 1234
   driverClassName: com.mysql.cj.jdbc.Driver

 jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL5Dialect
   hibernate:
    ddl-auto: update   

integrations:
    employees:
     url: http://localhost:8080/api